on:
  push:
    branches:
      - main
  pull_request:

name: "wemake lints"

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.17.0
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
